### ISSUE TITLE
[virtualbox] wrong mouse cursor rendering

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/packages-community#205]
Seems VirtualBox 5.1 has some issue with mouse cursor rendering. However this issue is with **upstream** and also visible with **Neon** and other live-medias ...

![mouse-cursor-vb51](https://cloud.githubusercontent.com/assets/5050022/16906861/36f96004-4cbe-11e6-8b30-d28289ff3835.png)

**Comment by kouros17** [comment]
I confirm it. I have the same problem on guest **manjaro xfce** and guest **arch xfce**.

**Comment by philmmanjaro** [comment]
Please comment also on https://www.virtualbox.org/ticket/15665

**Comment by oberon2007** [comment]
done

**Comment by philmmanjaro** [comment]
Fixed in r109189 for all my Linux VMs. See also: https://www.virtualbox.org/changeset/62588/vbox

**Comment by oberon2007** [comment]
For me the patch doesn't seem to fix it. Compiled and installed vbox **5.1.2-1.1** plus **host-dkms** and it's still the same when vbox-video is used in the guest. I've even installed 5.1.2-1.1 guest module in vbox and it's still the same:

![](http://imgur.com/Thijg5vl.png)

Am I missing something here?

**Comment by philmmanjaro** [comment]
Same or similar? Anyway, in v5.1.4 it should have been fixed. Please try the [current snapshot](https://www.virtualbox.org/wiki/Testbuilds).

**Comment by oberon2007** [comment]
Yes, exactly the same...

**Comment by kouros17** [comment]
Problem remains unsolved in v5.1.4.

**Comment by philmmanjaro** [comment]
Did you updated the drivers to 5.1.4 yet?

**Comment by philmmanjaro** [comment]
We should either [reopen ticket 15665](https://www.virtualbox.org/ticket/15665) or create a followup. However we should mention the used QT release as the patch I already tried before and resulted in non fixing the matter. Maybe they need more input.

**Comment by oberon2007** [comment]
I've reopened it. Did not have the opportunity to install 5.1.4 guest module, yet. But you did, right?

**Comment by philmmanjaro** [comment]
Yes, I did. It doesn't work.

**Comment by AshMj** [comment]
Hi there,
I have the issue with the cursor in the Virtual Box I described on the Manjaro forum:
https://forum.manjaro.org/t/2-little-bugs-after-a-full-update/7847

**Comment by oberon2007** [comment]
Yes, thank you @AshMj ! I hope the people at Oracle will find a solution soon :wink: 
https://www.virtualbox.org/ticket/15829

**Comment by kouros17** [comment]
Problem remains unsolved in 5.1.6

**Comment by philmmanjaro** [comment]
Seems to be a long runner then ...

**Comment by oberon2007** [comment]
Mircles do happen, though :laughing:
Fixed FINALLY with **vb-guest-modules 5.1.12** :champagne: :+1:

**Comment by oberon2007** [comment]
I must have been imagining... It's not fixed :-1:  Apparently this is a problem with qt in Arch, they are working on. See comments at the end: https://www.virtualbox.org/ticket/15829#comment:12

**Comment by philmmanjaro** [comment]
Seems to be fixed with **qt-5.8** update.

**Comment by Ste74** [comment]
Yeah now the cursor is ok on vbox

**Comment by oberon2007** [comment]
Halleluja! :laughing:
