### ISSUE TITLE
[firefox-kde] Firefox-kde 48.0-1 need to be rebuild

### ISSUE THREAD

**Issue by scachemaille** [manjaro/packages-community#212]
Firefox-kde 48 need to be rebuild against the last libvpx 1.6 otherwise it doesn't start.
https://forum.manjaro.org/t/firefox-48-with-multi-process-electrolysis-is-here/6933/4

**Comment by oberon2007** [comment]
Something's not right here. **firefox-kde 48.0-1** was built Aug 3, so it's newer than libvpx (Aug 1) @Kirek ?

**Comment by scachemaille** [comment]
libvpx wsa built on 1st august (on arch) but reached manjaro unstable only today.

**Comment by oberon2007** [comment]
hmm, I see :wink:

**Comment by oberon2007** [comment]
If you haven't started, yet, @Kirek , I can rebuild it now. I'll start anyway with 64bit. Just let me know in case you're at it, too :stuck_out_tongue_winking_eye:

**Comment by scachemaille** [comment]
seems that thunderbird-kde also need a rebuild.

**Comment by oberon2007** [comment]
firefox-kde 64bit is done. Building 32bit now...

**Comment by Kirek** [comment]
Ok, I will start rebuilding thunderbird-kde

**Comment by oberon2007** [comment]
OOps:
```
File "/build/firefox-kde/src/firefox-48.0/python/mozbuild/mozbuild/configure/util.py", line 199, in write
    if not buf.endswith('\n'):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 36: ordinal not in range(128)
*** Fix above errors and then restart with\
               "make -f client.mk build"
make[2]: *** [/build/firefox-kde/src/firefox-48.0/client.mk:374: configure] Error 1
make[2]: Leaving directory '/build/firefox-kde/src/firefox-48.0'
make[1]: *** [/build/firefox-kde/src/firefox-48.0/client.mk:387: /build/firefox-kde/src/firefox-48.0/obj-i686-pc-linux-gnu/Makefile] Error 2
make[1]: Leaving directory '/build/firefox-kde/src/firefox-48.0'
make: *** [client.mk:168: build] Error 2
```

**Comment by Kirek** [comment]
Weird, I will try to build it when I'm done with thunderbird

**Comment by Kirek** [comment]
```
Traceback (most recent call last):
  File "/build/firefox-kde/src/firefox-48.0/python/mozbuild/mozbuild/mozconfig.py", line 256, in read_mozconfig
    parsed = self._parse_loader_output(output)
  File "/build/firefox-kde/src/firefox-48.0/python/mozbuild/mozbuild/mozconfig.py", line 392, in _parse_loader_output
    assert current_type is not None
AssertionError
client.mk:114: *** missing separator.  Stop.
```

Just got this at packaging, with 64 and 32 bits, it's after unstable got the new glibc, maybe son regression?

**Comment by oberon2007** [comment]
Beh. So it's a different error now, great! My attempt to build the 32bit was before the [gcc update](https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20160801/007981.html) and after the [python update](https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20160801/007978.html) :laughing: The successful build of th 64bit before both. One could try downgrading the gcc and python packages and then try again to get a working 32bit version for now at least, but it's a bit messy maybe :wink:

**Comment by oberon2007** [comment]
Looks like **glibc** is not compatible to our current **fakeroot** pkg

**Comment by oberon2007** [comment]
similar to this: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=830912

**Comment by oberon2007** [comment]
upgrading **fakeroot** solves the ``dlsym`` errors. brings me back to the old ``UnicodeDecodeError`` from above.

**Comment by Ste74** [comment]
Aha it is ... `dlsym` is fakeroot the guilty .. compiled some pkgs and see this msg but the compiling finishing fine uff

**Comment by oberon2007** [comment]
I was wonder if we should just update **fakeroot** - but now on the other hand I suddenly have new **gcc** errors when building the rt kernel. So the question is, if it will actually be better to downgrade **glibc** and **gcc** ...

**Comment by oberon2007** [comment]
To me it looks like the **fakeroot** update is mostly 'cosmetic'...
https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/fakeroot&id=698efcd6bd865385f515e0cb0bbba515ea976f29

**Comment by oberon2007** [comment]
Most likely the ``UnicodeDecodeError`` needs to be fixed in the python code with something like ``content = content.decode('utf-8')`` or so - It's just strange that the error happens only for the 32bit version.

**Comment by oberon2007** [comment]
Something similar to this:
https://bug794713.bmoattachments.org/attachment.cgi?id=665811

**Comment by philmmanjaro** [comment]
I updated **fakeroot** now. Do we still see here an error?

**Comment by philmmanjaro** [comment]
At Arch Firefox just got updated. Also check their [changes](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/firefox&id=ba918ef5bd3d614be2dbc62b4efd9ca41bda014b)

**Comment by oberon2007** [comment]
The arch changes do not look related at first sight, but I'll try building it with these settings again anyway.
I already installed the updated **fakeroot** here yesterdayand that got me rid of the dlsym error. However what I am still running into (32bit only strangely) is this:
```
running build_ext
building 'psutil._psutil_linux' extension
creating build/temp.linux-i686-2.7
creating build/temp.linux-i686-2.7/psutil
gcc -pthread -fno-strict-aliasing -march=i686 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -march=i686 -mtune=generic -O2 -pipe -fstack-protector-strong -D_FORTIFY_SOURCE=2 -O2 -fPIC -DPSUTIL_VERSION=311 -I/usr/include/python2.7 -c psutil/_psutil_linux.c -o build/temp.linux-i686-2.7/psutil/_psutil_linux.o
Traceback (most recent call last):
  File "/build/firefox-kde/src/firefox-48.0/configure.py", line 94, in <module>
    sys.exit(main(sys.argv))
  File "/build/firefox-kde/src/firefox-48.0/configure.py", line 22, in main
    sandbox.run(os.path.join(os.path.dirname(__file__), 'moz.configure'))
  File "/build/firefox-kde/src/firefox-48.0/python/mozbuild/mozbuild/configure/__init__.py", line 214, in run
    self.include_file(path)
  File "/build/firefox-kde/src/firefox-48.0/python/mozbuild/mozbuild/configure/__init__.py", line 205, in include_file
    exec_(code, self)
  File "/build/firefox-kde/src/firefox-48.0/python/mozbuild/mozbuild/util.py", line 58, in exec_
    exec(object, globals, locals)
  File "/build/firefox-kde/src/firefox-48.0/moz.configure", line 7, in <module>
    include('build/moz.configure/init.configure')
  File "/build/firefox-kde/src/firefox-48.0/python/mozbuild/mozbuild/configure/__init__.py", line 459, in include_impl
    self.include_file(what)
  File "/build/firefox-kde/src/firefox-48.0/python/mozbuild/mozbuild/configure/__init__.py", line 205, in include_file
    exec_(code, self)
  File "/build/firefox-kde/src/firefox-48.0/python/mozbuild/mozbuild/util.py", line 58, in exec_
    exec(object, globals, locals)
  File "/build/firefox-kde/src/firefox-48.0/build/moz.configure/init.configure", line 171, in <module>
    @imports('distutils.sysconfig')
  File "/build/firefox-kde/src/firefox-48.0/python/mozbuild/mozbuild/configure/__init__.py", line 440, in decorator
    self._value_for(dummy)
  File "/build/firefox-kde/src/firefox-48.0/python/mozbuild/mozbuild/configure/__init__.py", line 285, in _value_for
    return self._value_for_depends(obj)
  File "/build/firefox-kde/src/firefox-48.0/python/mozbuild/mozbuild/util.py", line 919, in method_call
    cache[args] = self.func(instance, *args)
  File "/build/firefox-kde/src/firefox-48.0/python/mozbuild/mozbuild/configure/__init__.py", line 312, in _value_for_depends
    return func(*resolved_args)
  File "/build/firefox-kde/src/firefox-48.0/python/mozbuild/mozbuild/configure/__init__.py", line 749, in wrapped
    return new_func(*args, **kwargs)
  File "/build/firefox-kde/src/firefox-48.0/build/moz.configure/init.configure", line 218, in virtualenv_python
    manager.build(python)
  File "/build/firefox-kde/src/firefox-48.0/python/mozbuild/mozbuild/virtualenv.py", line 444, in build
    result = self._log_process_output(args, cwd=self.topsrcdir)
  File "/build/firefox-kde/src/firefox-48.0/python/mozbuild/mozbuild/virtualenv.py", line 174, in _log_process_output
    self.log_handle.write(line)
  File "/build/firefox-kde/src/firefox-48.0/python/mozbuild/mozbuild/configure/util.py", line 199, in write
    if not buf.endswith('\n'):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 36: ordinal not in range(128)
*** Fix above errors and then restart with\
               "make -f client.mk build"
```

**Comment by oberon2007** [comment]
The Arch changes are not changing anything as expected.
Still the same ``UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 36: ordinal not in range(128)``

**Comment by Kirek** [comment]
I'm rebuilding with the same settings and new fakeroot, I hadn't the unicode error so maybe it will build for me.

**Comment by oberon2007** [comment]
Strange if it does... Are you building with buildpkg or makepkg? I get the error in a fresh chroot.

**Comment by philmmanjaro** [comment]
Keep me posted. If some quirks are needed, let me know.

**Comment by Kirek** [comment]
The packaging error is gone with 64 bits, let's see now 32 bits...

**Comment by oberon2007** [comment]
64bit was never a problem for me. I pushed it to unstable yesterday already.

**Comment by Kirek** [comment]
The problem I had was the same with 64 and 32

**Comment by oberon2007** [comment]
yes. mysterious! :japanese_ogre:

**Comment by Kirek** [comment]
32 bits fine too, it seems it was related to the fakeroot warnings after all...
@oberon2007 I use devtools

**Comment by philmmanjaro** [comment]
So I assume this issue is solved but not yet uploaded ...

**Comment by Kirek** [comment]
It's uploading right now.

**Comment by oberon2007** [comment]
I don't know **devtools** at all. Apparently with **buildpkg** it is still an issue. Do they use compilers in different ways, maybe? Or is it possible that your python setup is different, @Kirek ? Would you mind trying again with buildpkg? The error happens early in the build process for me. Shortly after python environment is set up.

**Comment by Kirek** [comment]
devtools where the clean chroot build tools we used originally in manjaro, forked from arch devtools.
manjaro-tools was later forked from that for proper openrc support and other things.

just tested buildpkg, and with i686 it doesn't even start to compile 
`
==> Validating source files with sha256sums...
    firefox-48.0.source.tar.xz ... Passed
    mozconfig ... Passed
    firefox.desktop ... Passed
    firefox-install-dir.patch ... Passed
    vendor.js ... Passed
    firefox-symbolic.svg ... Passed
    firefox-gtk3-20.patch ... Passed
    no-libnotify.patch ... Passed
    kde.js ... Passed
    firefox-branded-icons.patch ... Passed
    firefox-kde.patch ... Passed
    firefox-no-default-ualocale.patch ... Passed
    mozilla-kde.patch ... Passed
    mozilla-language.patch ... Passed
    mozilla-nongnome-proxies.patch ... Passed
    pgo_fix_missing_kdejs.patch ... Passed
 --> Setting mirrorlist branch: unstable
**sudo: main: unable to allocate memory**
  -> Moving [firefox-kde-48.0-3-i686.pkg.tar.xz] -> [/var/cache/manjaro-tools/pkg/unstable/i686]
mv: cannot stat 'firefox-kde-48.0-3-i686.pkg.tar.xz': No such file or directory
  -> Archiving log files [firefox-kde-48.0-3-i686.log.tar.xz] ...
  -> Cleaning log files ...
==> Finished building [firefox-kde]
 --> Time make_pkg: 0.68 minutes
`
with 64 bits it started as usual

**Comment by Ste74** [comment]
So manjaro-tools ( buildpkg ) is wrong?  
Il 06/ago/2016 16:02, Ramon Buldó <notifications@github.com> ha scritto:devtools where the clean chroot build tools we used originally in manjaro, forked from arch devtools.
manjaro-tools was later forked from that for proper openrc support and other things.

just tested buildpkg, and with i686 it doesn't even start to compile 

==> Validating source files with sha256sums...
    firefox-48.0.source.tar.xz ... Passed
    mozconfig ... Passed
    firefox.desktop ... Passed
    firefox-install-dir.patch ... Passed
    vendor.js ... Passed
    firefox-symbolic.svg ... Passed
    firefox-gtk3-20.patch ... Passed
    no-libnotify.patch ... Passed
    kde.js ... Passed
    firefox-branded-icons.patch ... Passed
    firefox-kde.patch ... Passed
    firefox-no-default-ualocale.patch ... Passed
    mozilla-kde.patch ... Passed
    mozilla-language.patch ... Passed
    mozilla-nongnome-proxies.patch ... Passed
    pgo_fix_missing_kdejs.patch ... Passed
 --> Setting mirrorlist branch: unstable
**sudo: main: unable to allocate memory**
  -> Moving [firefox-kde-48.0-3-i686.pkg.tar.xz] -> [/var/cache/manjaro-tools/pkg/unstable/i686]
mv: cannot stat 'firefox-kde-48.0-3-i686.pkg.tar.xz': No such file or directory
  -> Archiving log files [firefox-kde-48.0-3-i686.log.tar.xz] ...
  -> Cleaning log files ...
==> Finished building [firefox-kde]
 --> Time make_pkg: 0.68 minutes

with 64 bits it started as usual

**Comment by Ste74** [comment]
Devtools and manjaro-tools are in conflict if remember right. 
Il 06/ago/2016 16:02, Ramon Buldó <notifications@github.com> ha scritto:devtools where the clean chroot build tools we used originally in manjaro, forked from arch devtools.
manjaro-tools was later forked from that for proper openrc support and other things.

just tested buildpkg, and with i686 it doesn't even start to compile 

==> Validating source files with sha256sums...
    firefox-48.0.source.tar.xz ... Passed
    mozconfig ... Passed
    firefox.desktop ... Passed
    firefox-install-dir.patch ... Passed
    vendor.js ... Passed
    firefox-symbolic.svg ... Passed
    firefox-gtk3-20.patch ... Passed
    no-libnotify.patch ... Passed
    kde.js ... Passed
    firefox-branded-icons.patch ... Passed
    firefox-kde.patch ... Passed
    firefox-no-default-ualocale.patch ... Passed
    mozilla-kde.patch ... Passed
    mozilla-language.patch ... Passed
    mozilla-nongnome-proxies.patch ... Passed
    pgo_fix_missing_kdejs.patch ... Passed
 --> Setting mirrorlist branch: unstable
**sudo: main: unable to allocate memory**
  -> Moving [firefox-kde-48.0-3-i686.pkg.tar.xz] -> [/var/cache/manjaro-tools/pkg/unstable/i686]
mv: cannot stat 'firefox-kde-48.0-3-i686.pkg.tar.xz': No such file or directory
  -> Archiving log files [firefox-kde-48.0-3-i686.log.tar.xz] ...
  -> Cleaning log files ...
==> Finished building [firefox-kde]
 --> Time make_pkg: 0.68 minutes

with 64 bits it started as usual

**Comment by Kirek** [comment]
Of course I had to remove devtools to test buildpkg, that doesn't tell me why buildpkg has this issue
``` --> Setting mirrorlist branch: unstable
sudo: main: unable to allocate memory
```
 with 32 bits an not with 64.

**Comment by oberon2007** [comment]
I had this same error before I tried again with ``-c`` flag. After that ``prepare()`` works fine and then it stops as described above.
Looks indeed like this is some kind of an issue with **manjaro-tools-pkg** ?

**Comment by oberon2007** [comment]
My full buildlog is here:
http://pastebin.com/raw/BcFia0Xs

**Comment by oberon2007** [comment]
I'd love to try building it with **makepkg**, but I have no 32bit system available. Do you, @philmmanjaro ?

**Comment by philmmanjaro** [comment]
@oberon2007: yes, I've a dual boot system. Both Manjaro with one for each Architecture. However I mostly use **x86_64**.

**Comment by Kirek** [comment]
Just tried buildpkg with a vm (I don't know why it doesn't agree with my laptop), and when building for i686 I have the same error as @oberon2007
